schema_version: 20180708
name: fn-x-region-image-resize
version: 0.0.5
runtime: java
build_image: abhirockzz/oci-java-sdk
run_image: fnproject/fn-java-fdk:jdk9-1.0.70
cmd: io.fnproject.example.ResizeImage::handle
format: http-stream
timeout: 100
triggers:
- name: resize
  type: http
  source: /resize
